name: Publish Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    environment: Publishing
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      # Automatically update version based on git tag
      - name: Set version from git tag
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
          pnpm version $VERSION --no-git-tag-version

      - name: Authenticate to GitHub Packages
        run: |
          echo "@anshul-veersa:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> ~/.npmrc

      - name: Publish to GitHub Packages
        run: pnpm publish --no-git-checks --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
